name: game
description: Game App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.2.4
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+2
  provider: ^6.0.3
  sqflite: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  ios: true
  web: true
  macos: true
  linux: true
  android: true
  windows: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-square.png"
  image_path_ios: "assets/images/logo-square.png"
  image_path_android: "assets/images/logo-square.png"
